error: clarify execution contexts
This patch classifies assuming execution contexts of all the Argobots functions
into three types:
 1. no specific context (assuming that Argobots has been initialized already),
 2. an execution stream (i.e., not on an external thread), and
 3. a yieldable thread (ULT).
This patch slighly changes the semantics of existing functions: for example,
there were functions that can be run on either an external thread or a ULT, but
such functions are updated so that they can be run on a tasklet (though a
tasklet will block the underlying execution stream).